name: base
channels:
  - schrodinger
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.7
  - anaconda-project=0.8.3
  - apbs=1.5
  - asn1crypto=0.24.0
  - astroid=2.2.5
  - astropy=3.2.1
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - babel=2.7.0
  - backcall=0.1.0
  - backports=1.0
  - backports.os=0.1.1
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.8.0
  - bitarray=1.0.1
  - bkcharts=0.2
  - blas=2.12
  - bleach=3.1.0
  - blosc=1.17.0
  - bokeh=1.3.4
  - boost=1.70.0
  - boost-cpp=1.70.0
  - boto=2.49.0
  - bottleneck=1.2.1
  - bzip2=1.0.8
  - ca-certificates=2019.6.16
  - cairo=1.16.0
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=1.2.1
  - clyent=1.2.2
  - colorama=0.4.1
  - conda=4.7.11
  - conda-build=3.18.9
  - conda-env=2.6.0
  - conda-package-handling=1.4.1
  - conda-verify=3.1.1
  - contextlib2=0.5.5
  - cryptography=2.7
  - curl=7.65.3
  - cycler=0.10.0
  - cython=0.29.13
  - cytoolz=0.10.0
  - dask=2.2.0
  - dask-core=2.2.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - distributed=2.2.0
  - docutils=0.15.2
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.5
  - fastcache=1.1.0
  - filelock=3.0.10
  - flask=1.1.1
  - fontconfig=2.13.1
  - freemol=1.158
  - freetype=2.10.0
  - fribidi=1.0.5
  - fsspec=0.4.1
  - future=0.17.1
  - get_terminal_size=1.0.0
  - gettext=0.19.8.1
  - gevent=1.4.0
  - glew=2.0.0
  - glib=2.58.3
  - glob2=0.7
  - gmp=6.1.2
  - gmpy2=2.1.0b1
  - graphite2=1.3.13
  - greenlet=0.4.15
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5py=2.9.0
  - harfbuzz=2.4.0
  - hdf5=1.10.5
  - heapdict=1.0.0
  - html5lib=1.0.1
  - icu=64.2
  - idna=2.8
  - imageio=2.5.0
  - imagesize=1.1.0
  - importlib_metadata=0.18
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.15.1
  - jeepney=0.4.1
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9c
  - json5=0.8.5
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - jupyterlab=1.0.5
  - jupyterlab_server=1.0.3
  - keyring=19.0.2
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - lazy-object-proxy=1.4.1
  - libarchive=3.3.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - liblief=0.9.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.17
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libtool=2.4.6
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.32
  - llvmlite=0.29.0
  - locket=0.2.0
  - lxml=4.4.1
  - lz4-c=1.8.3
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mccabe=0.6.1
  - mdtraj=1.9.3
  - mengine=1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.1.0
  - mkl_fft=1.0.14
  - mkl_random=1.0.4
  - mock=3.0.5
  - more-itertools=7.2.0
  - mpc=1.1.0
  - mpeg_encode=1
  - mpfr=4.0.2
  - mpmath=1.1.0
  - msgpack-python=0.6.1
  - mtz2ccp4_px=1.0
  - multipledispatch=0.6.0
  - navigator-updater=0.2.1
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.3
  - nltk=3.4.4
  - nose=1.3.7
  - notebook=6.0.0
  - numba=0.45.1
  - numexpr=2.7.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - numpydoc=0.9.1
  - olefile=0.46
  - openpyxl=2.6.2
  - openssl=1.1.1c
  - packaging=19.0
  - pandas=0.25.0
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.5.1
  - partd=1.0.0
  - patchelf=0.10
  - path.py=12.0.1
  - pathlib2=2.3.4
  - patsy=0.5.1
  - pcre=8.41
  - pdb2pqr=2.1.1
  - pep8=1.7.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.2.2
  - pixman=0.38.0
  - pkginfo=1.5.0.1
  - pluggy=0.12.0
  - ply=3.11
  - pmw=2.0.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - psutil=5.6.3
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.8.0
  - py-lief=0.9.0
  - pycairo=1.18.1
  - pycodestyle=2.5.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pycrypto=2.6.1
  - pycurl=7.43.0.2
  - pyflakes=2.1.1
  - pygments=2.4.2
  - pylint=2.3.1
  - pymbar=3.0.3
  - pymol=2.3.2
  - pyodbc=4.0.27
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - pysocks=1.7.0
  - pytables=3.5.2
  - pytest=5.1.0
  - pytest-arraydiff=0.3
  - pytest-astropy=0.5.0
  - pytest-doctestplus=0.3.0
  - pytest-openfiles=0.4.0
  - pytest-remotedata=0.3.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - python-libarchive-c=2.8
  - pytz=2019.2
  - pywavelets=1.0.3
  - pyyaml=5.1.2
  - pyzmq=18.0.2
  - qt=5.9.7
  - qtawesome=0.6.0
  - qtconsole=4.5.3
  - qtpy=1.9.0
  - rdkit=2019.03.4
  - readline=8.0
  - requests=2.22.0
  - rigimol=1.3
  - ripgrep=11.0.2
  - rope=0.14.0
  - ruamel_yaml=0.15.71
  - scikit-image=0.15.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - secretstorage=3.1.1
  - send2trash=1.5.0
  - setuptools=41.0.1
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.12.0
  - snappy=1.1.7
  - snowballstemmer=1.9.0
  - sortedcollections=1.1.2
  - sortedcontainers=2.1.0
  - soupsieve=1.9.2
  - sphinx=2.1.2
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.1
  - sphinxcontrib-websupport=1.1.2
  - spyder=3.3.6
  - spyder-kernels=0.5.1
  - sqlalchemy=1.3.7
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - sympy=1.4
  - tblib=1.4.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.33.0
  - traitlets=4.3.2
  - unicodecsv=0.14.1
  - unixodbc=2.3.7
  - urllib3=1.25.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.15.5
  - wheel=0.33.4
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - wurlitzer=1.0.3
  - xlrd=1.2.0
  - xlsxwriter=1.1.8
  - xlwt=1.3.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.8
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.2
  - zict=1.0.0
  - zipp=0.5.2
  - zlib=1.2.11
  - zstd=1.4.0
  - pip:
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
prefix: /home/bschroed/anaconda3_7

